/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IncidentType = {
  [k: string]: unknown;
} & {
  /**
   * field 3.23
   *
   * @minItems 1
   */
  incidentClassification?: [
    "cybersecurity-related" | "process_failure" | "system_failure" | "external_event" | "payment-related" | "other",
    ...(
      | "cybersecurity-related"
      | "process_failure"
      | "system_failure"
      | "external_event"
      | "payment-related"
      | "other"
    )[]
  ];
  /**
   * field 3.24 This field is required if 'incidentClassification' is other
   */
  otherIncidentClassification?: string;
  /**
   * field 3.25 Required if 'incidentClassification' is 'CYBERSECURITY_RELATED'.
   *
   * @minItems 1
   */
  threatTechniques?: [
    (
      | "social_engineering_including_phishing"
      | "ddos"
      | "identity_theft"
      | "data_encryption_for_impact_including_ransomware"
      | "resource_hijacking"
      | "data_exfiltration_and_manipulation_including_identity_theft"
      | "data_destruction"
      | "defacement"
      | "supply-chain_attack"
      | "other"
    ),
    ...(
      | "social_engineering_including_phishing"
      | "ddos"
      | "identity_theft"
      | "data_encryption_for_impact_including_ransomware"
      | "resource_hijacking"
      | "data_exfiltration_and_manipulation_including_identity_theft"
      | "data_destruction"
      | "defacement"
      | "supply-chain_attack"
      | "other"
    )[]
  ];
  /**
   * field 3.26 This field is required if 'threatTechniques' includes 'OTHER'
   */
  otherThreatTechniques?: string;
  /**
   * field 3.35 Required if the 'incidentClassification' is 'CYBERSECURITY_RELATED'
   */
  indicatorsOfCompromise?: string;
};

export interface DORAMajorIncidentReport {
  /**
   * field 1.1
   */
  incidentSubmission:
    | "initial_notification"
    | "intermediate_report"
    | "final_report"
    | "major_incident_reclassified_as_non-major";
  /**
   * field 1.15
   */
  reportCurrency?: "EUR" | "BGN" | "CZK" | "DKK" | "HUF" | "PLN" | "RON" | "ISK" | "CHF" | "NOK" | "SEK";
  submittingEntity: Entity;
  /**
   * @minItems 1
   */
  affectedEntity: [Entity1, ...Entity1[]];
  ultimateParentUndertaking?: Entity2;
  primaryContact: Contact;
  secondaryContact?: Contact1;
  incident: Incident;
  impactAssessment?: ImpactAssessment;
  /**
   * @minItems 1
   */
  reportingToOtherAuthorities?: [
    (
      | "police_law_enforcement"
      | "csirt"
      | "data_protection_authority"
      | "national_cybersecurity_agency"
      | "none"
      | "other"
    ),
    ...(
      | "police_law_enforcement"
      | "csirt"
      | "data_protection_authority"
      | "national_cybersecurity_agency"
      | "none"
      | "other"
    )[]
  ];
  /**
   * field 3.32  Required if reportingToOtherAuthorities includes 'OTHER'
   */
  reportingToOtherAuthoritiesOther?: string;
  /**
   * field 3.17
   */
  informationDurationServiceDowntimeActualOrEstimate?:
    | "actual_figures"
    | "estimates"
    | "actual_figures_and_estimates"
    | "no_information_available";
}
/**
 * field 1.2,1.3,
 */
export interface Entity {
  entityType?: "SUBMITTING_ENTITY" | "AFFECTED_ENTITY" | "ULTIMATE_PARENT_UNDERTAKING_ENTITY";
  /**
   * field 1.2, 1.5, 1.13
   */
  name?: string;
  /**
   * field 1.3a
   */
  code?: string;
  /**
   * @minItems 1
   */
  affectedEntityType?: [
    (
      | "credit_institution"
      | "payment_institution"
      | "exempted_payment_institution"
      | "account_information_service_provider"
      | "electronic_money_institution"
      | "exempted_electronic_money_institution"
      | "investment_firm"
      | "crypto-asset_service_provider"
      | "issuer_of_asset-referenced_tokens"
      | "central_securities_depository"
      | "central_counterparty"
      | "trading_venue"
      | "trade_repository"
      | "manager_of_alternative_investment_fund"
      | "management_company"
      | "data_reporting_service_provider"
      | "insurance_and_reinsurance_undertaking"
      | "insurance_intermediary_reinsurance_intermediary_and_ancillary_insurance_intermediary"
      | "institution_for_occupational_retirement_provision"
      | "credit_rating_agency"
      | "administrator_of_critical_benchmarks"
      | "crowdfunding_service_provider"
      | "securitisation_repository"
    ),
    ...(
      | "credit_institution"
      | "payment_institution"
      | "exempted_payment_institution"
      | "account_information_service_provider"
      | "electronic_money_institution"
      | "exempted_electronic_money_institution"
      | "investment_firm"
      | "crypto-asset_service_provider"
      | "issuer_of_asset-referenced_tokens"
      | "central_securities_depository"
      | "central_counterparty"
      | "trading_venue"
      | "trade_repository"
      | "manager_of_alternative_investment_fund"
      | "management_company"
      | "data_reporting_service_provider"
      | "insurance_and_reinsurance_undertaking"
      | "insurance_intermediary_reinsurance_intermediary_and_ancillary_insurance_intermediary"
      | "institution_for_occupational_retirement_provision"
      | "credit_rating_agency"
      | "administrator_of_critical_benchmarks"
      | "crowdfunding_service_provider"
      | "securitisation_repository"
    )[]
  ];
  /**
   * field 1.3b, 1.6, 1.14. The validation rules on the required field is not implemented
   */
  LEI?: string;
}
/**
 * field 1.4,1.5,1.6
 */
export interface Entity1 {
  entityType?: "SUBMITTING_ENTITY" | "AFFECTED_ENTITY" | "ULTIMATE_PARENT_UNDERTAKING_ENTITY";
  /**
   * field 1.2, 1.5, 1.13
   */
  name?: string;
  /**
   * field 1.3a
   */
  code?: string;
  /**
   * @minItems 1
   */
  affectedEntityType?: [
    (
      | "credit_institution"
      | "payment_institution"
      | "exempted_payment_institution"
      | "account_information_service_provider"
      | "electronic_money_institution"
      | "exempted_electronic_money_institution"
      | "investment_firm"
      | "crypto-asset_service_provider"
      | "issuer_of_asset-referenced_tokens"
      | "central_securities_depository"
      | "central_counterparty"
      | "trading_venue"
      | "trade_repository"
      | "manager_of_alternative_investment_fund"
      | "management_company"
      | "data_reporting_service_provider"
      | "insurance_and_reinsurance_undertaking"
      | "insurance_intermediary_reinsurance_intermediary_and_ancillary_insurance_intermediary"
      | "institution_for_occupational_retirement_provision"
      | "credit_rating_agency"
      | "administrator_of_critical_benchmarks"
      | "crowdfunding_service_provider"
      | "securitisation_repository"
    ),
    ...(
      | "credit_institution"
      | "payment_institution"
      | "exempted_payment_institution"
      | "account_information_service_provider"
      | "electronic_money_institution"
      | "exempted_electronic_money_institution"
      | "investment_firm"
      | "crypto-asset_service_provider"
      | "issuer_of_asset-referenced_tokens"
      | "central_securities_depository"
      | "central_counterparty"
      | "trading_venue"
      | "trade_repository"
      | "manager_of_alternative_investment_fund"
      | "management_company"
      | "data_reporting_service_provider"
      | "insurance_and_reinsurance_undertaking"
      | "insurance_intermediary_reinsurance_intermediary_and_ancillary_insurance_intermediary"
      | "institution_for_occupational_retirement_provision"
      | "credit_rating_agency"
      | "administrator_of_critical_benchmarks"
      | "crowdfunding_service_provider"
      | "securitisation_repository"
    )[]
  ];
  /**
   * field 1.3b, 1.6, 1.14. The validation rules on the required field is not implemented
   */
  LEI?: string;
}
/**
 * field 1.13,1.14
 */
export interface Entity2 {
  entityType?: "SUBMITTING_ENTITY" | "AFFECTED_ENTITY" | "ULTIMATE_PARENT_UNDERTAKING_ENTITY";
  /**
   * field 1.2, 1.5, 1.13
   */
  name?: string;
  /**
   * field 1.3a
   */
  code?: string;
  /**
   * @minItems 1
   */
  affectedEntityType?: [
    (
      | "credit_institution"
      | "payment_institution"
      | "exempted_payment_institution"
      | "account_information_service_provider"
      | "electronic_money_institution"
      | "exempted_electronic_money_institution"
      | "investment_firm"
      | "crypto-asset_service_provider"
      | "issuer_of_asset-referenced_tokens"
      | "central_securities_depository"
      | "central_counterparty"
      | "trading_venue"
      | "trade_repository"
      | "manager_of_alternative_investment_fund"
      | "management_company"
      | "data_reporting_service_provider"
      | "insurance_and_reinsurance_undertaking"
      | "insurance_intermediary_reinsurance_intermediary_and_ancillary_insurance_intermediary"
      | "institution_for_occupational_retirement_provision"
      | "credit_rating_agency"
      | "administrator_of_critical_benchmarks"
      | "crowdfunding_service_provider"
      | "securitisation_repository"
    ),
    ...(
      | "credit_institution"
      | "payment_institution"
      | "exempted_payment_institution"
      | "account_information_service_provider"
      | "electronic_money_institution"
      | "exempted_electronic_money_institution"
      | "investment_firm"
      | "crypto-asset_service_provider"
      | "issuer_of_asset-referenced_tokens"
      | "central_securities_depository"
      | "central_counterparty"
      | "trading_venue"
      | "trade_repository"
      | "manager_of_alternative_investment_fund"
      | "management_company"
      | "data_reporting_service_provider"
      | "insurance_and_reinsurance_undertaking"
      | "insurance_intermediary_reinsurance_intermediary_and_ancillary_insurance_intermediary"
      | "institution_for_occupational_retirement_provision"
      | "credit_rating_agency"
      | "administrator_of_critical_benchmarks"
      | "crowdfunding_service_provider"
      | "securitisation_repository"
    )[]
  ];
  /**
   * field 1.3b, 1.6, 1.14. The validation rules on the required field is not implemented
   */
  LEI?: string;
}
/**
 * field 1.7,1.8,1.9
 */
export interface Contact {
  /**
   * field 1.7, 1.10 - depending on the type of the contact primary or second
   */
  name?: string;
  /**
   * field 1.8, 1.11 - depending on the type of the contact primary or second
   */
  email: string;
  /**
   * field 1.9, 1.12 - depending on the type of the contact primary or second
   */
  phone?: string;
}
/**
 * field 1.10,1.11,1.12
 */
export interface Contact1 {
  /**
   * field 1.7, 1.10 - depending on the type of the contact primary or second
   */
  name?: string;
  /**
   * field 1.8, 1.11 - depending on the type of the contact primary or second
   */
  email: string;
  /**
   * field 1.9, 1.12 - depending on the type of the contact primary or second
   */
  phone?: string;
}
export interface Incident {
  /**
   * field 2.1
   */
  financialEntityCode?: string;
  /**
   * field 2.2
   */
  detectionDateTime?: string;
  /**
   * field 2.3
   */
  classificationDateTime?: string;
  /**
   * field 2.4
   */
  incidentDescription: string;
  /**
   * field2.10
   */
  otherInformation?: string;
  /**
   * @minItems 1
   */
  classificationTypes: [ClassificationType, ...ClassificationType[]];
  /**
   * field 2.9
   */
  isBusinessContinuityActivated?: boolean;
  /**
   * field 3.2
   */
  incidentOccurrenceDateTime?: string;
  /**
   * field 3.15
   */
  incidentDuration?: string;
  /**
   * field 2.8
   */
  originatesFromThirdPartyProvider?: string;
  /**
   * field 2.7
   */
  incidentDiscovery?:
    | "it_security"
    | "staff"
    | "internal_audit"
    | "external_audit"
    | "clients"
    | "financial_counterparts"
    | "third-party_provider"
    | "attacker"
    | "monitoring_systems"
    | "authority_agency_law_enforcement_body"
    | "other";
  /**
   * field 3.1
   */
  competentAuthorityCode?: string;
  incidentType?: IncidentType;
  /**
   * field 4.1
   *
   * @minItems 1
   */
  rootCauseHLClassification?: [
    "malicious_actions" | "process_failure" | "system_failure_malfunction" | "human_error" | "external_event",
    ...("malicious_actions" | "process_failure" | "system_failure_malfunction" | "human_error" | "external_event")[]
  ];
  /**
   * field 4.2
   *
   * @minItems 1
   */
  rootCausesDetailedClassification?: [
    (
      | "malicious_actions_deliberate_internal_actions"
      | "malicious_actions_deliberate_physical_damage_manipulation_theft"
      | "malicious_actions_fraudulent_actions"
      | "process_failure_insufficient_monitoring_or_failure_of_monitoring_and_control"
      | "process_failure_insufficient_unclear_roles_and_responsibilities"
      | "process_failure_ICT_risk_management_process_failure"
      | "process_failure_insufficient_or_failure_of_ict_operations_and_ict_security_operations"
      | "process_failure_insufficient_or_failure_of_ict_project_management"
      | "process_failure_inadequacy_of_internal_policies_procedures_and_documentation"
      | "process_failure_inadequate_ict_systems_acquisition_development_and_maintenance"
      | "process_failure_other"
      | "system_failure_hardware_capacity_and_performance"
      | "system_failure_hardware_maintenance"
      | "system_failure_hardware_obsolescence_ageing"
      | "system_failure_software_compatibility_configuration"
      | "system_failure_software_performance"
      | "system_failure_network_configuration"
      | "system_failure_physical_damage"
      | "system_failure_other"
      | "human_error_omission"
      | "human_error_mistake"
      | "human_error_skills_knowledge"
      | "human_error_inadequate_human_resources"
      | "human_error_miscommunication"
      | "human_error_other"
      | "external_event_natural_disasters_force_majeure"
      | "external_event_third-party_failures"
      | "external_event_other"
    ),
    ...(
      | "malicious_actions_deliberate_internal_actions"
      | "malicious_actions_deliberate_physical_damage_manipulation_theft"
      | "malicious_actions_fraudulent_actions"
      | "process_failure_insufficient_monitoring_or_failure_of_monitoring_and_control"
      | "process_failure_insufficient_unclear_roles_and_responsibilities"
      | "process_failure_ICT_risk_management_process_failure"
      | "process_failure_insufficient_or_failure_of_ict_operations_and_ict_security_operations"
      | "process_failure_insufficient_or_failure_of_ict_project_management"
      | "process_failure_inadequacy_of_internal_policies_procedures_and_documentation"
      | "process_failure_inadequate_ict_systems_acquisition_development_and_maintenance"
      | "process_failure_other"
      | "system_failure_hardware_capacity_and_performance"
      | "system_failure_hardware_maintenance"
      | "system_failure_hardware_obsolescence_ageing"
      | "system_failure_software_compatibility_configuration"
      | "system_failure_software_performance"
      | "system_failure_network_configuration"
      | "system_failure_physical_damage"
      | "system_failure_other"
      | "human_error_omission"
      | "human_error_mistake"
      | "human_error_skills_knowledge"
      | "human_error_inadequate_human_resources"
      | "human_error_miscommunication"
      | "human_error_other"
      | "external_event_natural_disasters_force_majeure"
      | "external_event_third-party_failures"
      | "external_event_other"
    )[]
  ];
  /**
   * field 4.3
   *
   * @minItems 1
   */
  rootCausesAdditionalClassification?: [
    (
      | "monitoring_of_policy_adherence"
      | "monitoring_of_third-party_service_providers"
      | "monitoring_and_verification_of_remediation_of_vulnerabilities"
      | "identity_and_access_management"
      | "encryption_and_cryptography"
      | "logging"
      | "failure_in_specifying_accurate_risk_tolerance_levels"
      | "insufficient_vulnerability_and_threat_assessments"
      | "inadequate_risk_treatment_measures"
      | "poor_management_of_residual_ict_risks"
      | "vulnerability_and_patch_management"
      | "change_management"
      | "capacity_and_performance_management"
      | "ict_asset_management_and_information_classification"
      | "backup_and_restore"
      | "error_handling"
      | "inadequate_ict_systems_acquisition_development_and_maintenance"
      | "insufficient_or_failure_of_software_testing"
    ),
    ...(
      | "monitoring_of_policy_adherence"
      | "monitoring_of_third-party_service_providers"
      | "monitoring_and_verification_of_remediation_of_vulnerabilities"
      | "identity_and_access_management"
      | "encryption_and_cryptography"
      | "logging"
      | "failure_in_specifying_accurate_risk_tolerance_levels"
      | "insufficient_vulnerability_and_threat_assessments"
      | "inadequate_risk_treatment_measures"
      | "poor_management_of_residual_ict_risks"
      | "vulnerability_and_patch_management"
      | "change_management"
      | "capacity_and_performance_management"
      | "ict_asset_management_and_information_classification"
      | "backup_and_restore"
      | "error_handling"
      | "inadequate_ict_systems_acquisition_development_and_maintenance"
      | "insufficient_or_failure_of_software_testing"
    )[]
  ];
  /**
   * field 4.4
   */
  rootCausesOther?: string;
  /**
   * field 4.5
   */
  rootCausesInformation?: string;
  /**
   * field 4.7 - format YYYY-MM-DDThh:mm:ssZ
   */
  rootCauseAddressingDateTime?: string;
  /**
   * field 4.6
   */
  incidentResolutionSummary?: string;
  /**
   * field 4.8 - format YYYY-MM-DDThh:mm:ssZ
   */
  incidentResolutionDateTime?: string;
  /**
   * field 4.9
   */
  incidentResolutionVsPlannedImplementation?: string;
  /**
   * field 4.10
   */
  assessmentOfRiskToCriticalFunctions?: string;
  /**
   * field 4.11
   */
  informationRelevantToResolutionAuthorities?: string;
  /**
   * field 4.14
   */
  financialRecoveriesAmount?: number;
  /**
   * field 4.13
   */
  grossAmountIndirectDirectCosts?: number;
  /**
   * field 4.15
   */
  recurringNonMajorIncidentsDescription?: string;
  /**
   * field 4.16; format YYYY-MM-DDThh:mm:ssZ
   */
  recurringIncidentDate?: string;
}
export interface ClassificationType {
  /**
   * field 2.5
   */
  classificationCriterion:
    | "clients_financial_counterparts_and_transactions_affected"
    | "geographical_spread"
    | "data_losses"
    | "critical_services_affected"
    | "economic_impact"
    | "reputational_impact"
    | "duration_and_service_downtime";
  /**
   * field 2.6
   *
   * @minItems 1
   */
  countryCodeMaterialityThresholds?: [
    (
      | "AT"
      | "BE"
      | "BG"
      | "HR"
      | "CY"
      | "CZ"
      | "DK"
      | "EE"
      | "ES"
      | "FI"
      | "FR"
      | "DE"
      | "GR"
      | "HU"
      | "IS"
      | "IE"
      | "IT"
      | "LI"
      | "LT"
      | "LU"
      | "LV"
      | "MT"
      | "NL"
      | "NO"
      | "PL"
      | "PT"
      | "RO"
      | "SE"
      | "SI"
      | "SK"
    ),
    ...(
      | "AT"
      | "BE"
      | "BG"
      | "HR"
      | "CY"
      | "CZ"
      | "DK"
      | "EE"
      | "ES"
      | "FI"
      | "FR"
      | "DE"
      | "GR"
      | "HU"
      | "IS"
      | "IE"
      | "IT"
      | "LI"
      | "LT"
      | "LU"
      | "LV"
      | "MT"
      | "NL"
      | "NO"
      | "PL"
      | "PT"
      | "RO"
      | "SE"
      | "SI"
      | "SK"
    )[]
  ];
  /**
   * field 3.18
   *
   * @minItems 1
   */
  memberStatesImpactType?: [
    (
      | "clients"
      | "financial_counterparts"
      | "branch_of_the_financial_entity"
      | "financial_entities_within_the_group_carrying_out_activities_in_the_respective_member_state"
      | "financial_market_infrastructure"
      | "third-party_providers_that_may_be_common_to_other_financial_entities"
    ),
    ...(
      | "clients"
      | "financial_counterparts"
      | "branch_of_the_financial_entity"
      | "financial_entities_within_the_group_carrying_out_activities_in_the_respective_member_state"
      | "financial_market_infrastructure"
      | "third-party_providers_that_may_be_common_to_other_financial_entities"
    )[]
  ];
  /**
   * field 3.19
   */
  memberStatesImpactTypeDescription?: string;
  /**
   * field 3.20
   *
   * @minItems 1
   */
  dataLosseMaterialityThresholds?: [
    "availability" | "authenticity" | "integrity" | "confidentiality",
    ...("availability" | "authenticity" | "integrity" | "confidentiality")[]
  ];
  /**
   * field 3.21
   */
  dataLossesDescription?: string;
  /**
   * field 3.13 , if field 2.5 mention reputation impact
   *
   * @minItems 1
   */
  reputationalImpactType?: [
    (
      | "the_major_ict-related_incident_has_been_reflected_in_the_media"
      | "the_major_ict-related_incident_has_resulted_in_repetitive_complaints_from_different_clients_or_financial_counterparts_on_client-facing_services_or_critical_business_relationships"
      | "the_financial_entity_will_not_be_able_to_or_is_likely_not_to_be_able_to_meet_regulatory_requirements_as_a_result_of_the_major_ict-related_incident"
      | "the_financial_entity_will_or_is_likely_to_lose_clients_or_financial_counterparts_with_a_material_impact_on_its_business_as_a_result_of_the_major_ict-related_incident"
    ),
    ...(
      | "the_major_ict-related_incident_has_been_reflected_in_the_media"
      | "the_major_ict-related_incident_has_resulted_in_repetitive_complaints_from_different_clients_or_financial_counterparts_on_client-facing_services_or_critical_business_relationships"
      | "the_financial_entity_will_not_be_able_to_or_is_likely_not_to_be_able_to_meet_regulatory_requirements_as_a_result_of_the_major_ict-related_incident"
      | "the_financial_entity_will_or_is_likely_to_lose_clients_or_financial_counterparts_with_a_material_impact_on_its_business_as_a_result_of_the_major_ict-related_incident"
    )[]
  ];
  /**
   * field 3.14
   */
  reputationalImpactDescription?: string;
  /**
   * field 4.12
   */
  economicImpactMaterialityThreshold?: string;
}
export interface ImpactAssessment {
  /**
   * field 3.8
   */
  hasImpactOnRelevantClients?: boolean;
  serviceImpact?: ServiceImpact;
  /**
   * field 3.22
   */
  criticalServicesAffected?: string;
  affectedAssets?: AffectedAssets;
  /**
   * field 3.27
   */
  affectedFunctionalAreas?: string;
  /**
   * field 3.28
   */
  isAffectedInfrastructureComponents?: "yes" | "no" | "information_not_available";
  /**
   * field 3.29
   */
  affectedInfrastructureComponents?: string;
  /**
   * field 3.30
   */
  isImpactOnFinancialInterest?: "yes" | "no" | "information_not_available";
}
export interface ServiceImpact {
  /**
   * field 3.3
   */
  serviceRestorationDateTime?: string;
  /**
   * field 3.16
   */
  serviceDowntime?: string;
  /**
   * field 3.33
   */
  isTemporaryActionsMeasuresForRecovery?: boolean;
  /**
   * field 3.34
   */
  descriptionOfTemporaryActionsMeasuresForRecovery?: string;
}
/**
 * field 3.4, 3.5, 3.6, 3.7, 3.9, 3.10, 3.11, 3.12
 */
export interface AffectedAssets {
  affectedClients?: NumberPercentageType;
  affectedFinancialCounterparts?: NumberPercentageType1;
  affectedTransactions?: NumberPercentageType2;
  /**
   * field 3.11
   */
  valueOfAffectedTransactions?: number;
  /**
   * field 3.12
   *
   * @minItems 1
   */
  numbersActualEstimate?: [
    (
      | "actual_figures_for_clients_affected"
      | "actual_figures_for_financial_counterparts_affected"
      | "actual_figures_for_transactions_affected"
      | "estimates_for_clients_affected"
      | "estimates_for_financial_counterparts_affected"
      | "estimates_for_transactions_affected"
      | "no_impact_on_clients"
      | "no_impact_on_financial_counterparts"
      | "no_impact_on_transactions"
    ),
    ...(
      | "actual_figures_for_clients_affected"
      | "actual_figures_for_financial_counterparts_affected"
      | "actual_figures_for_transactions_affected"
      | "estimates_for_clients_affected"
      | "estimates_for_financial_counterparts_affected"
      | "estimates_for_transactions_affected"
      | "no_impact_on_clients"
      | "no_impact_on_financial_counterparts"
      | "no_impact_on_transactions"
    )[]
  ];
}
/**
 * field 3.4, 3.5
 */
export interface NumberPercentageType {
  /**
   * generic
   */
  number?: number;
  /**
   * generic
   */
  percentage?: number;
}
/**
 * field 3.6, 3.7
 */
export interface NumberPercentageType1 {
  /**
   * generic
   */
  number?: number;
  /**
   * generic
   */
  percentage?: number;
}
/**
 * field 3.9, 3.10
 */
export interface NumberPercentageType2 {
  /**
   * generic
   */
  number?: number;
  /**
   * generic
   */
  percentage?: number;
}
